spring:
  application:
      name: doubaoBackend
  # default dev
  profiles:
    active: dev
  # session
  store-type: redis
  session:
    timeout: 2592000 # 30 days
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dosou_db
    username: root
    password: 123456
  # Redis
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 dats timeout
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # logic delete field
      logic-delete-value: 1 # 1 is deleted
      logic-not-delete-value: 0 # 0 is not deleted